baseurl: '/'
permalink: pretty
title: 'C2SI'

logo:
  mobile: "images/logo/c2si-logo-mobile.png"
  mobile_height: "32px"
  mobile_width: "32px"
  # header logo image
  desktop: "images/logo/c2si-logo-main.png" 
  desktop_height: "37px"
  desktop_width: "140px"

home: 
  limit_services: 8

collections:
  services:
    output: true
    sort_by: weight
  team:
    output: true
  publications:
    output: true
    # sort_by: year

defaults:
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"
  - scope:
      path: ""
      type: "publication"
    values:
      layout: "publication"

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
